apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: supportClaw-home-pvc
  labels:
    app: supportClaw
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
